import { AsyncData, AsyncDataOptions, NuxtError, useAsyncData } from 'nuxt/app';
import { computed, unref, type WatchSource } from 'vue';

/**
 * Type alias for the result returned by useAsyncData.
 * @template T - The type of the data returned by the function.
 */
type AsyncDataResult<T> = AsyncData<T | null, NuxtError | null>;

/**
 * Options accepted by useAsyncDataWrapper.
 */
export type UseAsyncDataWrapperOptions = {
  /**
   * Prefix prepended to every `useAsyncData` key generated by the wrapper.
   * Useful to avoid key collisions when wrapping several objects that expose
   * functions with the same name.
   */
  keyPrefix?: string;
};

/**
 * Transforms an object's Promise-returning functions into functions compatible with useAsyncData.
 *
 * Only includes functions that return Promises; other properties are excluded.
 *
 * For each function in the object:
 * - If the function returns a Promise and takes no arguments, it becomes a function that accepts optional AsyncDataOptions.
 * - If the function returns a Promise and takes arguments, it becomes a function that accepts an argsSupplier and optional AsyncDataOptions.
 *
 * @template T - The type of the object.
 */
export type AsyncDataWrapper<T> = {
  [
    K in keyof T as T[K] extends (...args: any[]) => Promise<any> ? K : never
  ]: T[K] extends (...args: infer Args) => Promise<infer R>
    ? Args extends []
      ? /**
         * Functions without arguments.
         * @param options - Optional AsyncDataOptions to configure useAsyncData.
         * @returns AsyncDataResult containing the data, status state, and error.
         */
        (options?: AsyncDataOptions<R>) => AsyncDataResult<R>
      : /**
         * Functions with arguments.
         * @param argsSupplier - A function that returns the arguments array for the original function.
         * @param options - Optional AsyncDataOptions to configure useAsyncData.
         * @returns AsyncDataResult containing the data, status state, and error.
         */
        (
          argsSupplier: () => Args,
          options?: AsyncDataOptions<R>,
        ) => AsyncDataResult<R>
    : never;
};

/**
 * Wraps an object's Promise-returning functions to integrate with Nuxt's useAsyncData.
 *
 * It transforms the functions of the provided object into functions that can be used within a Nuxt application,
 * leveraging the reactivity and data fetching capabilities of useAsyncData.
 *
 * Wrapped functions must be called during component setup, as they rely on Nuxt's `useAsyncData`.
 *
 * @template T - The type of the object.
 * @param obj - The object containing functions that return Promises.
 * @param wrapperOptions - Optional wrapper options, such as a key prefix.
 * @returns An object with the same function names as the original object, but wrapped to work with useAsyncData.
 *
 * @example
 * ```typescript
 * const originalObject = {
 *   async fetchData() { ... },
 *   async getItem(id: number) { ... },
 * };
 * const wrappedObject = useAsyncDataWrapper(originalObject, { keyPrefix: 'original' });
 * ```
 */
export function useAsyncDataWrapper<T extends Record<string, any>>(
  obj: T,
  wrapperOptions?: UseAsyncDataWrapperOptions,
): AsyncDataWrapper<T> {
  const keyPrefix = wrapperOptions?.keyPrefix
    ? `${wrapperOptions.keyPrefix}-`
    : '';
  const composable = {} as AsyncDataWrapper<T>;
  const functionNames = getFunctionNames(obj);
  for (const functionName of functionNames) {
    const originalFunction = obj[functionName].bind(obj);
    const wrappedFunction = getWrappedFunction(
      functionName,
      originalFunction,
      keyPrefix,
    );
    (composable as any)[functionName] = wrappedFunction;
  }
  return composable;
}

function getFunctionNames(obj: any): string[] {
  const functionNameSet = new Set<string>();
  let currentObj = obj;
  while (currentObj && currentObj !== Object.prototype) {
    const descriptors = Object.getOwnPropertyDescriptors(currentObj);
    for (const key of Object.keys(descriptors)) {
      // Exclude constructor and non-function properties without invoking getters
      const descriptor = descriptors[key];
      if (key !== 'constructor' && typeof descriptor.value === 'function') {
        functionNameSet.add(key);
      }
    }
    currentObj = Object.getPrototypeOf(currentObj);
  }
  return Array.from(functionNameSet);
}

function getWrappedFunction(
  functionName: string,
  originalFunction: (...args: any[]) => Promise<any>,
  keyPrefix: string,
): (...args: any[]) => AsyncDataResult<any> {
  const dataKey = `${keyPrefix}${functionName}`;
  return (...args: any[]) => {
    if (typeof args[0] === 'function') {
      // Function with arguments: first argument is argsSupplier, second is options
      const argsSupplier = args[0];
      const options = args[1];
      return getWrappedFunctionWithArgs(
        dataKey,
        originalFunction,
        argsSupplier,
        options!,
      );
    }
    if (originalFunction.length > 0) {
      throw new TypeError(
        `useAsyncDataWrapper: function "${functionName}" requires an argsSupplier (a function returning the arguments array) as its first argument, but received ${typeof args[0]}.`,
      );
    }
    // Function without arguments: options may be the first argument
    const options = args[0];
    return getWrappedFunctionWithoutArgs(dataKey, originalFunction, options!);
  };
}

function getWrappedFunctionWithArgs<T extends (...args: any[]) => Promise<any>>(
  dataKey: string,
  originalFunction: T,
  argsSupplier: () => Parameters<T>,
  options: AsyncDataOptions<Awaited<ReturnType<T>>>,
): AsyncDataResult<Awaited<ReturnType<T>>> {
  // Reactive reference to arguments
  const argsRef = computed(() => argsSupplier!());
  // Unique key for useAsyncData
  const dataKeyRef = computed(
    () => `${dataKey}-${stringifyArgs(argsRef.value)}`,
  );
  // Call useAsyncData with the generated key and function
  const asyncDataResult = useAsyncData(
    dataKeyRef.value,
    async () => originalFunction(...unref(argsRef)),
    {
      // Spread additional options first so user options are not lost
      ...options,
      // Re-execute when arguments change, merged with user-provided watch sources
      watch: [argsRef, ...normalizeWatchSources(options?.watch)],
    },
  );
  return asyncDataResult;
}

function getWrappedFunctionWithoutArgs<T extends () => Promise<any>>(
  dataKey: string,
  originalFunction: T,
  options: AsyncDataOptions<Awaited<ReturnType<T>>>,
): AsyncDataResult<Awaited<ReturnType<T>>> {
  // For functions without arguments
  const asyncDataResult = useAsyncData(
    dataKey,
    async () => originalFunction(),
    {
      // Spread additional options
      ...options,
    },
  );
  return asyncDataResult;
}

/**
 * Normalizes the watch option into an array of watch sources.
 */
function normalizeWatchSources(
  watch: AsyncDataOptions<any>['watch'],
): (object | WatchSource<unknown>)[] {
  if (!watch) {
    return [];
  }
  return Array.isArray(watch) ? watch : [watch];
}

/**
 * Serializes arguments into a stable string used to build unique useAsyncData keys.
 *
 * Unlike JSON.stringify, this handles Map, Set, Date, functions, and symbols,
 * and sorts object keys so that key order does not affect the result.
 *
 * @throws {TypeError} If the arguments contain circular references.
 */
function stringifyArgs(value: unknown): string {
  return stringifyValue(value, new WeakSet<object>());
}

function stringifyValue(value: unknown, visited: WeakSet<object>): string {
  switch (typeof value) {
    case 'undefined':
      return 'undefined';
    case 'number':
    case 'boolean':
      return String(value);
    case 'bigint':
      return `${value}n`;
    case 'string':
      return JSON.stringify(value);
    case 'symbol':
      return `symbol(${value.description ?? ''})`;
    case 'function':
      return `fn(${value.name || 'anonymous'})`;
    case 'object': {
      if (value === null) {
        return 'null';
      }
      if (visited.has(value)) {
        throw new TypeError(
          'useAsyncDataWrapper: arguments contain circular references',
        );
      }
      visited.add(value);
      if (value instanceof Date) {
        return Number.isNaN(value.getTime())
          ? 'Date(invalid)'
          : `Date(${value.toISOString()})`;
      }
      if (value instanceof Map) {
        const entries = Array.from(value, ([key, val]) => {
          const serializedKey = stringifyValue(key, visited);
          const serializedValue = stringifyValue(val, visited);
          return `[${serializedKey},${serializedValue}]`;
        });
        return `Map(${entries.join(',')})`;
      }
      if (value instanceof Set) {
        const values = Array.from(value, val => stringifyValue(val, visited));
        return `Set(${values.join(',')})`;
      }
      if (Array.isArray(value)) {
        const values = value.map(val => stringifyValue(val, visited));
        return `[${values.join(',')}]`;
      }
      const keys = Object.keys(value).sort();
      const entries = keys.map(key => {
        const serializedKey = JSON.stringify(key);
        const serializedValue = stringifyValue(
          (value as Record<string, unknown>)[key],
          visited,
        );
        return `${serializedKey}:${serializedValue}`;
      });
      return `{${entries.join(',')}}`;
    }
  }
}
